name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      checks: write
      contents: read
    steps:
      - &checkout
        name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Set up Compiler
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "**/vcpkg.json"
      - name: CMake Configure
        run: cmake -S . -B build -G "Ninja Multi-Config" -DMORAI_BUILD_TESTS=ON -DMORAI_BUILD_EXAMPLES=ON -DMORAI_BUILD_DOCS=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DVCPKG_MANIFEST_FEATURES=examples
      - name: Build Debug
        run: cmake --build build --config Debug
      - name: Build Release
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build --output-on-failure --no-compress-output -C Release --output-junit junit.xml
      - name: Publish test results
        if: (!cancelled())
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        with:
          check_name: Test results windows-msvc
          comment_mode: off
          files: build/junit.xml
      - name: Upload test results
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: test-results-windows-msvc
          path: build/junit.xml
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install WiX v6
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix extension add WixToolset.UI.wixext
        shell: powershell
      - name: Pack
        run: cpack --config build/CPackConfig.cmake -C Release
  build-linux:
    runs-on: ${{ matrix.os }}

    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-24.04]
        compiler: [gcc, clang]
    steps:
      - *checkout
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Install Ubuntu dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build libncurses-dev cmake
      - name: Install Compiler
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get update && sudo apt-get install -y g++
          else
            sudo apt-get update && sudo apt-get install -y clang
          fi
        shell: bash
      - name: CMake Configure
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
          cmake -S . -B build -G "Ninja Multi-Config" -DMORAI_BUILD_TESTS=ON -DMORAI_BUILD_EXAMPLES=ON -DMORAI_BUILD_DOCS=ON
        shell: bash
      - name: Build Debug
        run: cmake --build build --config Debug
      - name: Build Release
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build --output-on-failure --no-compress-output -C Release --output-junit junit.xml
      - name: Publish test results
        if: (!cancelled())
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Test results ${{ matrix.os }}-${{ matrix.compiler }}
          comment_mode: off
          files: build/junit.xml
      - name: Upload test results
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.compiler }}
          path: build/junit.xml
      - name: Pack
        run: cpack --config build/CPackConfig.cmake -C Release
