name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-pack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-24.04]
        compiler: [msvc, gcc, clang]
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-24.04
            compiler: msvc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Set up Compiler
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt-get update && sudo apt-get install -y ninja-build libncurses-dev cmake
      - name: Install GCC
        if: matrix.os == 'ubuntu-24.04' && matrix.compiler == 'gcc'
        run: sudo apt-get update && sudo apt-get install -y g++
      - name: Install Clang
        if: matrix.os == 'ubuntu-24.04' && matrix.compiler == 'clang'
        run: sudo apt-get update && sudo apt-get install -y clang
      - name: Configure CMake
        if: matrix.compiler == 'msvc'
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DMORAI_BUILD_TESTS=ON -DMORAI_BUILD_EXAMPLES=ON
      - name: Configure CMake
        if: matrix.compiler != 'msvc'
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DMORAI_BUILD_TESTS=ON -DMORAI_BUILD_EXAMPLES=ON
        shell: bash
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure -T Test --no-compress-output --output-junit
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/Testing/**/*.xml
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: build/Testing/**/*.xml
      - name: Pack
        run: cpack --config build/CPackConfig.cmake
